name: planets_animations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family : archivo
      fonts:
        - asset: assets/fonts/Archivo_Black/ArchivoBlack-Regular.ttf
    - family : lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family : Soupro
      fonts:
        - asset: assets/fonts/Source_Code_Pro/static/SourceCodePro-Regular.ttf
